### ISSUE TITLE
另一种思路安装archlinuxarm 

### ISSUE THREAD

**Issue by armgong** [cattyhouse/N1-install#1]
1 直接利用armbian image文件刷U盘， 
2 mount U盘的系统分区，复制 armbian的 lib/modules/ 和lib/firmware
3 删除其他文件夹，下载archlinuxarm的tar.gz，解压到系统根目录 
4复制 armbian的 lib/modules/ 和lib/firmware 到 相对应的位置
5 编辑archlinux里的各种配置文件（ip 等等）
5 重启，就可以U盘引导了
这样利用了armbian的内核和archlinux的系统环境，如果需要进一步那就再自己编译内核，至于安装到EMMC 没有试过，有兴趣的可以自己试试从armbian里边复制相应的功能也不复杂

**Comment by cattyhouse** [comment]
我最初的版本就是直接解压archlinuxarm.tar.gz到U盘 Or MMC，你可以看看history。这样做的不好的地方就是，不够干净，那个userland里面带了很多乱七八糟的东西。

**Comment by armgong** [comment]
userland 直接删除 就要armbian的 lib/modules/ 和lib/firmware

**Comment by armgong** [comment]
armbian userland别的内容都不需要

**Comment by cattyhouse** [comment]
我说的是archlinuxarm的userland有很多乱七八糟的东西，看注释：

https://archlinuxarm.org/platforms/armv8/generic
