### ISSUE TITLE
我没明白具体怎么操作

### ISSUE THREAD

**Issue by heaion** [cattyhouse/N1-install#2]
我用的是和斐讯一样的s905TV盒子，移动魔百盒G2 -40F.
请问有其他的更具体的图文，或视频吗？这样更容易学习。
可以给我留给联系方式吗？我想具体问问

**Comment by cattyhouse** [comment]
弄个 armbian 优盘, 能启动的话, 就可以按照本文安装 arch linux

**Comment by heaion** [comment]
可以加我qq，细聊吗？？
我刚接触有很多问题，QQ：2049593359
或微信，
万分感谢
