### ISSUE TITLE
蓝牙

### ISSUE THREAD

**Issue by Damenly** [cattyhouse/N1-install#3]
请问蓝牙可以正常工作吗? 我手动添加了armbian的/lib/firmware/BCM4345C0.hcd 还是不行
[root@alarm ~]# hciconfig -a
hci0:   Type: Primary  Bus: SDIO
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN
        RX bytes:0 acl:0 sco:0 events:0 errors:0
        TX bytes:0 acl:0 sco:0 commands:0 errors:0
        Features: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
        Packet type: DM1 DH1 HV1
        Link policy:
        Link mode: SLAVE ACCEPT

**Comment by cattyhouse** [comment]
删除 armbian 的 firmware, 安装

https://archlinux.jerryxiao.cc/aarch64/firmware-phicomm-n1-7-4-any.pkg.tar.xz

**Comment by Damenly** [comment]
@cattyhouse My bad. 我原来用得是armbian的dtb.其实只需要修改过的dtb文件就可以了. 
谢谢分享的教程.
