### ISSUE TITLE
赶紧把5.8内核撤包吧，没法启动

### ISSUE THREAD

**Issue by onlymash** [cattyhouse/N1-install#4]
防止再有人滚挂，还是把5.8先撤掉吧（哭
https://archlinux.jerryxiao.cc/aarch64

**Comment by LordPenguin666** [comment]
我滚挂了呀（哭

**Comment by cattyhouse** [comment]
5.8.1 可以启动的, 

原因:

https://github.com/archlinux-jerry/pkgbuilds/commit/97ba3821f895c81a43a8810e2e525f252590781b

**Comment by cattyhouse** [comment]
Linux n1 5.8.1-1-justin #2 SMP Thu Aug 13 22:49:16 CST 2020 aarch64 GNU/Linux
 14:48:53 up 2 days, 15:34,  2 users,  load average: 0.00, 0.00, 0.00

**Comment by cattyhouse** [comment]
你可以用我编译的, 下载用 pacman -U 安装 .

https://kr1.us.to/kernel/

https://kr1.us.to/kernel/readme.txt (精简了很多东西, 纯 server 用.)

**Comment by onlymash** [comment]
你这个内核确实能用，比较精简，体积小了不少

**Comment by cattyhouse** [comment]
> 你这个内核确实能用，比较精简，体积小了不少

所以 jerry 的那个 5.8.1 还是不能用吗? 能再测试下么, 讲道理, 他的那个 5.8.1 是我修改了 PKGBUILD之后编译的, 应该可以用的.

**Comment by onlymash** [comment]
> > 你这个内核确实能用，比较精简，体积小了不少
> 
> 所以 jerry 的那个 5.8.1 还是不能用吗? 能再测试下么, 讲道理, 他的那个 5.8.1 是我修改了 PKGBUILD之后编译的, 应该可以用的.

昨天滚挂了退到5.7后没再试过

**Comment by cattyhouse** [comment]
> > > 你这个内核确实能用，比较精简，体积小了不少
> > 
> > 
> > 所以 jerry 的那个 5.8.1 还是不能用吗? 能再测试下么, 讲道理, 他的那个 5.8.1 是我修改了 PKGBUILD之后编译的, 应该可以用的.
> 
> 昨天滚挂了退到5.7后没再试过

Jerry那个确实不能启动, 已经撤下来了, 解决中.

**Comment by onlymash** [comment]
最近买了个x86机器，n1作为网关的使命结束了。
于是装了个xfce桌面看视频，CPU占用很高，这个内核是不是GPU驱动不行？

**Comment by just4id** [comment]
Hi all, 最新的5.8.5好用不？

**Comment by jsxcl** [comment]
修不好了吗？

**Comment by cattyhouse** [comment]
后续准备用 5.4 LTS, 有时间我编译个内核.

**Comment by Allegorii** [comment]
请问能用linux-tkg的内核吗？

**Comment by cattyhouse** [comment]
编译了 5.9.9 已经已经可以启动了. 下载地址:

https://kr1.us.to/kernel/
