### ISSUE TITLE
请教一个桌面的问题

### ISSUE THREAD

**Issue by JustinWuCN** [cattyhouse/N1-install#9]
在内核仓库里问桌面的问题好像不太合适,但是我确实不知道去哪里问.
通过这个教程,安装成功了,但是在我安装桌面环境时,一直启动不起来.

安装的显示驱动是xf86-video-armsoc-meson,
使用lxdm启动lxde-gtk3.
lxdm可以显示出图形,但是没有鼠标,登录进去不能显示菜单,没有鼠标光标,但是按鼠标右键可以出来一个黑色的菜单.
使用xfce4桌面,什么都显示不出来.
是要配置哪里呢?
需要从哪里开始分析问题?

**Comment by cattyhouse** [comment]
https://wiki.archlinux.org/title/General_recommendations#Graphical_user_interface

**Comment by JustinWuCN** [comment]
网上查到的一个讨论帖,https://forum.odroid.com/viewtopic.php?t=26969
好像mali驱动不起来.
可以看看你安装的是什么显示驱动吗?
我试着安装xf86-video-armsoc-meson和xf86-video-odroid-c2.
二个都驱动不起来.

**Comment by cattyhouse** [comment]
我不玩桌面

**Comment by JustinWuCN** [comment]
好的,谢谢!
我再网上查一查
